### ISSUE TITLE
Unable to edit value

### ISSUE THREAD

**Issue by thanapongp** [MarioZ/MadMilkman.Ini#10]
I keep getting 'Property or indexer 'IniItemCollection<IniKey>.this[string]' cannot be assigned to -- it is read only".

Here is my code:

``` c#
IniOptions options = new IniOptions();
IniFile file = new IniFile(options);

file.Load(@"Save Example.ini");

file.Sections["Section 1"].Keys["Key 1.1"] = "TEST";
```

How am I going to edit the value in the file? I can't seem to find it anywhere on documentation.

**Comment by MarioZ** [comment]
Try this:

``` c#
file.Sections["Section 1"].Keys["Key 1.1"].Value = "TEST";
```

Does this solve your issue?

**Comment by thanapongp** [comment]
Works perfectly! Thank you for quick answer!
