### ISSUE TITLE
Having trouble writing back to the file (Duplication)

### ISSUE THREAD

**Issue by sollaholla** [MarioZ/MadMilkman.Ini#11]
Hi, I just started using this library, and I'm having some trouble.

I'm trying to write to the ini file, and it seems to be working, except it's duplicating the entire file, while still writing to the original section of the file.

Is there something I'm doing wrong?

**Comment by sollaholla** [comment]
Nevermind. It was because I was calling File.Load() multiple times.

**Comment by MarioZ** [comment]
I'm glad you were able to solve your issue.
Also as an FYI this behaviour is intentional, it can enable you to merge (combine) multiple INI files into a single INI file.
