### ISSUE TITLE
[Help] Writing to ini from static function.

### ISSUE THREAD

**Issue by sollaholla** [MarioZ/MadMilkman.Ini#12]
I have a static method that gets called, and I want to write to a .ini from that method. Is this possible? 
I know this really isn't a question about MadMilkman.Ini and more of a question from someone who isn't super advanced in C#, but thanks in advance.

**Comment by sollaholla** [comment]
Lol I wasn't calling file.Save(filepath); _facepalm_

**Comment by MarioZ** [comment]
I'm glad you were able to solve this, if you need anything else please feel free to contact me again.
Also please note that I'm located in GMT+1 time zone, but nevertheless I'll reply to you as soon as possible.
