### ISSUE TITLE
Clear a section

### ISSUE THREAD

**Issue by ryanjleo** [MarioZ/MadMilkman.Ini#13]
is there any way to clear a section as you can do wtih each key

**Comment by miere43** [comment]
Didn't quite got what you want, but you can clear section using `Clear()` method:

``` c#
ini.Sections["abcd"].Keys.Clear();
```

**Comment by ryanjleo** [comment]
realise you can clear a key but you cant clear a section eg was looking for a routine like  
For Each section In iniFile.Sections
                        If section.Name = "Name" Then
section.clear()
End if
Next

**Comment by MarioZ** [comment]
Hi,

I presume you want to delete the whole section, is that correct?
In that case try the following:

``` vb.net
iniFile.Sections.Remove("Name")
```

Or:

``` vb.net
Dim section = iniFile.Sections("Name")
iniFile.Sections.Remove(section)
```

Does this solve your issue?

**Comment by ryanjleo** [comment]
Thanks Mario that will work.

Regards Ryan
