### ISSUE TITLE
[Question] Merging dlls.

### ISSUE THREAD

**Issue by sollaholla** [MarioZ/MadMilkman.Ini#14]
Could I get your permission to use ILMerge to merge your DLL into mine? 
I'm making mods for a video game, and it would be really cool if I could reduce the amount of DLL files I need.

**Comment by MarioZ** [comment]
Hi, yes of course, feel free to merge MadMilkman.Ini with your DLL.

Also just in case you're interested you could achieve the same without using ILMerge, by using MadMilkman.Ini.dll as embedded resources.

Last, approach that you could also consider is to download the MadMilkman.Ini project, add it to your solution, add a project reference to it from your DLL project and then modify a bit that project reference in your ".csproj" file. This approach is described on the following link:
[Combining Multiple .NET Assemblies](http://www.codeproject.com/Tips/888790/Combining-Multiple-NET-Assemblies)
