### ISSUE TITLE
Can't read value when giving section name and key name as string. 

### ISSUE THREAD

**Issue by kcvinker** [MarioZ/MadMilkman.Ini#17]
Hi,
Thanks for this library. I have tested it in my vs2013. But i can't read value when i give section name and key name as string. I can read only when i give integers as section name and key name. But i see that in your examples, you used string for section name and key name. What to do ?
Note : I am using VB.Net

**Comment by MarioZ** [comment]
Hi,
Do you receive any error when using a string indexer?
Can you provide an input INI file which you're loading and a snippet code that reproduces your issue so that I can investigate this issue?

**Comment by MarioZ** [comment]
Hi,

I presume that this matter is resolved so I'll close this ticket.
If it's not, please let me know.

Regards,
Mario
