### ISSUE TITLE
Exception thrown: 'System.NullReferenceException' in when use ini.Sections(node).Keys(value).Value.ToString

### ISSUE THREAD

**Issue by 2pay** [MarioZ/MadMilkman.Ini#20]
I want check exist before get key value:
```vb.net
Dim kValue As String = ini.Sections(sName).Keys(kName).Value.ToString
 If (kValue = Nothing) Then
    getConfig = kValue
else
    getConfig = ''
end if
```
return error : Exception thrown: System.NullReferenceException at Dim kValue As String = ini.Sections(sName).Keys(kName).Value.ToString

how to check exist or null key before get it.

**Comment by MarioZ** [comment]
Hi,

Note that both `Sections` and `Keys` collections will return `Nothing` if the item of the specified name does not exist.  
You can use `Contains` method to check if it does exist:
```vb.net
Dim kValue As String = Nothing

If ini.Sections.Contains(sName) Then
    Dim section = ini.Sections(sName)
    If section.Keys.Contains(sName) Then
        Dim key = section.Keys(kName)
        kValue = key.Value
    End If
End If

If kValue IsNot Nothing Then
    getConfig = kValue
Else
    getConfig = ""
End If
```
Or you can try accessing the required item and then checking if it's `Nothing`:
```vb.net
Dim kValue As String = Nothing

Dim section = ini.Sections(sName)
If section IsNot Nothing Then

    Dim key = section.Keys(kName)
    If key IsNot Nothing Then
        kValue = key.Value
    End If
End If

If kValue IsNot Nothing Then
    getConfig = kValue
Else
    getConfig = ""
End If
```
Last, in case you're using a newer version of VB.NET (Visual Studio 2015 or later), then you could use the null-conditional operators:
```vb.net
Dim kValue As String = ini.Sections(sName)?.Keys(kName)?.Value

If kValue IsNot Nothing Then
    getConfig = kValue
Else
    getConfig = ""
End If
```
I hope this helps.

Regards,  
Mario

**Comment by MarioZ** [comment]
Hi,
I presume that you were able to solve your issue so I'll close this ticket.
If you need anything else, please let me know.

Regards,
Mario

**Comment by 2pay** [comment]
Thankyou, this error resolved.
