### ISSUE TITLE
Having problem to update value

### ISSUE THREAD

**Issue by NoSoup4you2** [MarioZ/MadMilkman.Ini#21]
I have no problem reading file but for some reason i can not update the values. I searched and found a simple sample
` Dim ini As New IniFile

ini.Load("C:\Users\Dropbox\Vodex\CNAME\cname.ini")
        ini.Sections("Error").Keys("value").Value = "yes"` 

When i debug and step over it i hit the ini.Load but it never hits the ini.Sections and the value is never updated ?
What am i missing ?

**Comment by MarioZ** [comment]
Hi,

Note that `IniFile` object is an in-memory representation of that loaded INI file.
In order to see any changes that are done in that object, you need to save it.
In other words, try using something like the following:

```vb.net
Dim ini As New IniFile

ini.Load("C:\Users\Dropbox\Vodex\CNAME\cname.ini")
ini.Sections("Error").Keys("value").Value = "yes"

ini.Save("C:\Users\Dropbox\Vodex\CNAME\cname.ini")
```

Does this solve your issue?

Regards,
Mario

**Comment by NoSoup4you2** [comment]
Yes that did the trick for me. All the samples o the internet in different forums did miss that last step
And I did not see anything that said it was in mem only till executing .save

thanks

**Comment by MarioZ** [comment]
Hi,

I'm glad that helped.

Also in case you're interested, I would recommend you to take a look at the first few pages of [MadMilkman.Ini.Documentation](https://github.com/MarioZ/MadMilkman.Ini/raw/master/MadMilkman.Ini.Documentation.zip) (**1 Getting Started**, **2 Overview** and **3 Code Samples** pages)

I hope this helps as well.

Regards,
Mario
