### ISSUE TITLE
decrypt file?

### ISSUE THREAD

**Issue by gogo8888** [MarioZ/MadMilkman.Ini#23]
hi there
is there a way to decrypt an encrypted ini file?

**Comment by MarioZ** [comment]
Hi,

Yes, you just need to set the same password before loading the encrypted INI file.
For example see the following:

``` csharp
// Write encrypted INI file.
IniOptions options1 = new IniOptions();
options1.EncryptionPassword = "pass";

IniFile file1 = new IniFile(options1);
file1.Sections.Add("Sample").Keys.Add("Secret", "My Hidden Value");
file1.Save("Sample.ini");


// Read encrypted INI file.
IniOptions options2 = new IniOptions();
options2.EncryptionPassword = "pass";

IniFile file2 = new IniFile(options2);
file2.Load("Sample.ini");
Console.WriteLine(file2.Sections[0].Keys[0].Value);
```

Does this solve your issue?

Regards,
Mario

**Comment by gogo8888** [comment]
Hi there,
Thank you kindly for responding.   I'm trying to find a way to save the encrypted ini file in the clear.
I understand how to read the values from an encrypted ini, but now i want to write the whole thing out in the clear.   I suppose i could just use textwriter and manually write out all the values to a new ini file, but thought maybe you had something built in that i can use to make it easier

thank you for your time

**Comment by MarioZ** [comment]
Hi,

Unfortunately, I did not quite get that. Can you explain what do you mean by "save the encrypted ini file in the clear"?
What do you mean by "clear"?

Nevertheless, the provided sample codes shows how to write an encrypted "Sample.ini" file and also how to read that encrypted "Sample.ini" file.
I'm just guessing here, but is it possible that you want to load the encrypted INI file and save it as decrypted?

If yes, then you could try something like the following:

``` csharp
// Read encrypted INI file.
IniOptions options = new IniOptions();
options.EncryptionPassword = "pass";

IniFile file1 = new IniFile(options);
file1.Load("Encrypted.ini");


// Write plain (decrypted) INI file.
IniFile file2 = new IniFile();

foreach (IniSection sec1 in file1.Sections)
    file2.Sections.Add(sec1.Copy(file2));

file2.Save("Decrypted.ini");
```

I hope this helps.

Regards,
Mario

**Comment by gogo8888** [comment]
This is perfect, thank you!

**Comment by gogo8888** [comment]
last question
is it possible to have multiline values?
for example:

[test]
testkey1=some really long
text that spans over many
many lines.

thank you for all of your help

**Comment by MarioZ** [comment]
Hi,

Unfortunately no, that is not possible with INI format.
However, you could perhaps have something like the following INI file:
```cfg
[test]
testkey1=some really long
testkey1=text that spans over many
testkey1=many lines.
```
And use it as following:
``` csharp
IniOptions options = new IniOptions();
options.KeyDuplicate = IniDuplication.Allowed;

IniFile ini = new IniFile(options);
ini.Load("Sample.ini");

IniSection sec = ini.Sections["test"];
string testvalue1 = string.Join("\n",
    sec.Keys.Where(key => key.Name == "testkey1").Select(key => key.Value));

Console.WriteLine(testvalue1);
```
Or perhaps something like the following:
```cfg
[test]
testkey1={ some really long, text that spans over many, many lines. }
```
And use it as a following:
``` csharp
IniFile ini = new IniFile();
ini.Load("Sample.ini");

IniSection sec = ini.Sections["test"];
IniKey key = sec.Keys["testkey1"];

string testvalue1;
string[] values;
if (key.TryParseValue(out values))
    testvalue1 = string.Join("\n", values);
else
    testvalue1 = key.Value;

Console.WriteLine(testvalue1);
```
I hope this suits your needs.

Regards,
Mario

**Comment by gogo8888** [comment]
This is exactly what i was looking for, thank you for your time!

**Comment by imkaka** [comment]
Thank You So Much @MarioZ
