### ISSUE TITLE
How to read from Encrypted File. c#

### ISSUE THREAD

**Issue by imkaka** [MarioZ/MadMilkman.Ini#24]
* I want to load the file which is encrypted outside with a password.
* Open and use it in the Current C# File
Please help me @MarioZ

**Comment by MarioZ** [comment]
Hi,

Please check #23.
Does this answer your question?
Let me know if you need anything else.

Regards,
Mario

**Comment by imkaka** [comment]
There is one more question I have a .ini file written in notepad in proper format, I want to load and encrypt it.
So that later i can read the the encrypted file.

**Comment by MarioZ** [comment]
Hi,

You'll want to do something like this:
``` csharp

// Read plain (decrypted) INI file.
IniFile inputIni = new IniFile();
inputIni.Load(@"C:\plain_notepad_file.ini");
            
// Write encrypted INI file.
IniOptions options = new IniOptions();
options.EncryptionPassword = "1234";

IniFile outputIni = new IniFile(options);
foreach (IniSection inputSec in inputIni.Sections)
    outputIni.Sections.Add(inputSec.Copy(outputIni));

outputIni.Save(@"C:\encrypted_file.ini");
```
I hope this helps.

Regards,
Mario

**Comment by imkaka** [comment]
Thank You for your help @MarioZ
