### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by CollinChaffin** [MarioZ/MadMilkman.Ini#29]
Not sure why this is so touch even these days without having to rewrite file streams from scratch.....

Need to produce a simple ini with potentially blank sections containing only a linefeed that look like this:

```
[Section1](FULL CARRIAGE RETURN+LINEFEED HERE)
(LINEFEED HERE)
[Section2](FULL CARRIAGE RETURN+LINEFEED HERE)
(LINEFEED HERE)
```

Have it other than this assembly if I use a linefeed char as the key name even without a value still insists on placing the equals sign, otherwise would be correct.

Is this possible with this assembly, and if so what is the absolute simplest method without having to perform so much manual string manipulation that it's no different than just performing the standard filestream writer?

TIA!

**Comment by MarioZ** [comment]
Hi,

Can you try the following:
```c#
var ini = new IniFile();

var sec1 = ini.Sections.Add("Section1");

var sec2 = ini.Sections.Add("Section2");
sec2.TrailingComment.EmptyLinesBefore = 1;

ini.Save("Sample.ini");
```
The resulting "Sample.ini" will look like the following:
```cfg
[Section1](CR+LF)
(CR+LF)
[Section2](CR+LF)
```
I hope this suits your needs.

Regards
Mario

**Comment by CollinChaffin** [comment]
Ahh perfect @MarioZ I should have dug into the code a bit more I missed those options!  Thanks!
