### ISSUE TITLE
Deleting duplicate section based on key value

### ISSUE THREAD

**Issue by Palshee** [MarioZ/MadMilkman.Ini#30]
Hello, 
I am having some trouble with this and I was wondering if I am doing something wrong or if there is a better way to do this.
Suppose I have the following sections, which all have the same section name...

```
[Test]
Length=10
Color=Red
Size=1
[Test]
Length=20
Color=Blue
Size=2
[Test]
Length=30
Color=Green
Size=3
```

What if I wanted to delete the 2nd section, where Color=blue?

I tried something like this...

```
For Each section As IniSection In ini.Sections.Where(Function(s) s.Name = "Radius")
    If section.Keys("Color").Value = "Blue" Then
        ini.Sections.Remove(section)
    End If
Next
```
I am getting the following error in VisualStudio:
```
An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll

Additional information: Collection was modified; enumeration operation may not execute.
```

Am I doing it wrong?

**Comment by Palshee** [comment]
I figured it out. I was doing it wrong. You cannot modify a collection while looping through it with a For Each loop. You have to use a For Loop.
This is how I deleted a section based on it's key, where the section can be a duplicate.

```vb.net
For i as Integer = 0 to ini.Sections("Section").Count - 1
    If ini.Sections(i).Keys("KeyName").Value = ("Value")  Then
        ini.Sections.RemoveAt(i)
Next
```

**Comment by MarioZ** [comment]
Hi,

Yes that is right, you can't delete inside the "For Each".
Anyway, I'm glad you were able to solve this issue.
Let me know if you need anything else.

Regards,
Mario
