### ISSUE TITLE
Example of exception handling for keys that do not exist

### ISSUE THREAD

**Issue by privatewid** [MarioZ/MadMilkman.Ini#31]
Hi, 

Your component is working really well for me but I have an issue when determining how to handle a `NullReferenceException` in VB.NET.

For example, I have global variables in my project and want to assign values that are stored in the ini file.  This works great when the Keys are present in the ini file but when they are not I get a `NullReferenceException`.  I'd like to be able to handle this better and inform the user that a key was not found in the ini file.

Here's a block of code I'm using...

```vb
With iniFile.Sections("Settings")
   ...
   strTest = .Keys("Test").Value
   ...
End With
```

If the key 'Test' doesn't exist or isn't spelled correctly in the 'Settings' section of the ini file, I get the `NullReferenceException`.   Is there a nice way to check if the key 'Test' exists first before attempting to load the value? I'd like to be able to deal with Key's that don't exist without it throwing the exception

Many thanks for this brilliant component.

**Comment by MarioZ** [comment]
Hi,

You can use this:

```vb
strTest = .Keys("Test")?.Value
```

Which will result in `strTest ` being `Nothing` when it doesn't exist.

Or, you could use this:

```vb
    Dim settings = iniFile.Sections("Settings")
    If (settings.Keys.Contains("Test")) Then strTest = settings.Keys("Test").Value
```

Or, you could use this:

```vb
    Dim settings = iniFile.Sections("Settings")
    Dim key = settings.Keys("Test")
    If (key IsNot Nothing) Then strTest = key.Value
```

I hope this helps, let me know if you need anything else.

Regards,
Mario

**Comment by privatewid** [comment]
Thanks Mario this worked great!
