### ISSUE TITLE
Add Key without Section?

### ISSUE THREAD

**Issue by PIN0L33KZ** [MarioZ/MadMilkman.Ini#35]
Hi,

is there a way to add a Key and value without adding a Section to the file?

Greetings!

**Comment by MarioZ** [comment]
Hi,

No, you need to create an IniSection object. But, you can have keys that belong to the non-named or global section.

For example, try this:

```cs
IniFile file = new IniFile();

file.Sections.Add(
    new IniSection(file, IniSection.GlobalSectionName,
        new IniKey(file, "Key1", "Value1"),
        new IniKey(file, "Key2", "Value2")));

file.Save("output.ini");
```

Does this solve your issue?

Regards,
Mario

**Comment by PIN0L33KZ** [comment]
Hi again,

nope not really. The thing is, I’m kind of abuse your library. I don’t use it to read/write ini-files but files with the same format just without the sections. But I have a solution that works simply fine for me. I’ve created a Section, added all Keys and Values I’ve needed and saved “the ini-file” into a string, then I deleted the Section in the String and wrote the String into a file. Same thing with reading the file. I've read the file into a string, added the Section and read out the keys and values.

But thanks for your reply :)
