### ISSUE TITLE
Multilingual support 

### ISSUE THREAD

**Issue by workingmoon500** [MarioZ/MadMilkman.Ini#36]
I love the library you made.
I speak Korean, but the characters are broken like a question mark.
Even now, it is enough software,
If you provide multilingual support, I think more people will like it.

Thank you for making something good.
Written by your new followers.

**Comment by MarioZ** [comment]
Hi,

Can you send me a snippet code or a small project that reproduces your issue?

It's possible that you'll need to change the encoding, for example, like this:

```cs
IniFile file = new IniFile(new IniOptions() { Encoding = Encoding.Unicode });
```

Regards,
Mario

**Comment by workingmoon500** [comment]
Thank you for your kindness.

It works nicely.

You are so cool.
you are handsome.

`IniFile memoIni = new IniFile(new IniOptions() { Encoding = Encoding.UTF8 });`
