### ISSUE TITLE
Is this project licensed under the MIT License, or the Apache License, Version 2.0?

### ISSUE THREAD

**Issue by DrewNaylor** [MarioZ/MadMilkman.Ini#37]
While the "LICENSE" file says it's under the MIT License, some files (`MadMilkman.Ini/IniFile.cs`, `MadMilkman.Ini/IniOptions.cs`, and `MadMilkman.Ini/Properties/AssemblyInfo.cs`, to be specific) say they're under the Apache License, Version 2.0 in their copyright/license boilerplate. Sorry if this sounds demanding.

**Comment by gemboxsoftware-dev-team** [comment]
Hi Drew,

The current latest version ([1.0.6](https://github.com/MarioZ/MadMilkman.Ini/releases/tag/1.0.6)) was released under the Apache License 2.0.

However, with the next version (2.0.0) I'll be switching to MIT.
I planed to already release the new version, but unfortunately, I'm currently unable to obtain any free time for myself, you know how it is with kids ... :)

**Comment by MarioZ** [comment]
Hi Drew,

The current latest version ([1.0.6](https://github.com/MarioZ/MadMilkman.Ini/releases/tag/1.0.6)) was released under the Apache License 2.0.

However, with the next version (2.0.0) I'll be switching to MIT.
I planed to already release the new version, but unfortunately, I'm currently unable to obtain any free time for myself, you know how it is with kids ... :)

**Comment by DrewNaylor** [comment]
Ah, I see. That's understandable. Just wasn't sure about which license the current state of the code was under.

**Comment by MarioZ** [comment]
The only public commit I did, for now, was license update, see [commits](https://github.com/MarioZ/MadMilkman.Ini/commits/master).
Apologize for the confusion, I should have started working on a new version in a new branch.
