### ISSUE TITLE
unable to use values with equal-sign

### ISSUE THREAD

**Issue by Floyddotnet** [MarioZ/MadMilkman.Ini#4]
Example:

[sektion]
key="Data Source=server;Initial Catalog=catalog;Integrated Security=SSPI"

**Comment by MarioZ** [comment]
Hi,

Unfortunately the problem is that by default a semicolon character (';') represents the beginning of a comment text. So the result is the following:

``` csharp
IniFile ini = new IniFile();
ini.Load("Sample.ini");
IniKey key = ini.Sections["sektion"].Keys["key"];

// Returns: "Data Source=server
Console.WriteLine(key.Value);
// Returns: Initial Catalog=catalog;Integrated Security=SSPI"
Console.WriteLine(key.LeadingComment.Text);
```

However as a workaround you could specify a different character for comment's beginning, for example:

``` csharp
// Specify '#' to be a character for comment's beginning.
IniOptions options = new IniOptions() { CommentStarter = IniCommentStarter.Hash };
IniFile ini = new IniFile(options);
ini.Load("Sample.ini");
```

Or:

``` csharp
// Specify some other character for comment's beginning.
IniOptions options = new IniOptions() { CommentStarter = (IniCommentStarter)'!' };
IniFile ini = new IniFile(options);
ini.Load("Sample.ini");
```

Does this solve your issue?
If not please let me know.

Regards,
Mario

**Comment by MarioZ** [comment]
Hi,

I presume that this matter is resolved so I'll close this ticket.
Again if it's not let me know.

Regards,
Mario

**Comment by Floyddotnet** [comment]
Is it not better to ignore Comment-Signes in Quotes?

**Comment by MarioZ** [comment]
Hi,

Please try again with [this latest version](https://github.com/MarioZ/MadMilkman.Ini/raw/master/MadMilkman.Ini.zip).
Does this solve your issue?

Regards,
Mario

**Comment by MarioZ** [comment]
Hi,

I presume that this matter is resolved so I'll close this ticket.
Again if it's not let me know.

Regards,
Mario
