### ISSUE TITLE
System.IO.IOException process cannot access the file

### ISSUE THREAD

**Issue by n1lsik** [MarioZ/MadMilkman.Ini#41]
Hello! Sometimes I get an error that it is impossible to write to a file, but previously I used your library in a console application with the .NET Framework 4.7.2 and it always worked fine. And now I am using the library with a Windows Forms application and .NET Framework 4.8.0

My code (VB.NET):

```vb
Dim ini1 As New IniFile()
ini1.Load("set.ini")
ini1.Sections("main").Keys("valusd").Value = usdRate
ini1.Save("set.ini")
```

And the error log:

```
System.IO.IOException: The process cannot access the file 'D:\soft\set.ini' because the file is in use by another process.
    in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
    in MadMilkman.Ini.IniFile.Save(String filePath)
    in ReloadSoft.Form1.GetUsdRate() in D:\VS\project1\Form1.vb:line 191
    in ReloadSoft.Form1.ConfigAndUsdRateTimer_Tick(Object sender, EventArgs e) in D:\VS\project1\Form1.vb:line 260
    at System.Windows.Forms.Timer.OnTick(EventArgs e)
    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by MarioZ** [comment]
Hi Stepan,

First, you should verify what application is loving the file.
For example, use one of the suggestions from here:
https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

If it ends up that it's your application, can you send me a small Visual Studio project that reproduces your issue so that I can investigate it?

Regards,
Mario

**Comment by n1lsik** [comment]
Thanks for the answer! To be honest, I still didn’t understand what exactly the problem was. I used several methods to check if the file locked and it wasn't locked. Perhaps this was due to the fact that in the directory above I had node js projects and the npm made the attributes read-only. I changed this and now it seems to work
