### ISSUE TITLE
.CHM documentation is empty

### ISSUE THREAD

**Issue by miere43** [MarioZ/MadMilkman.Ini#7]
All sections are just empty.

![hh_2016-04-02_13-33-51](https://cloud.githubusercontent.com/assets/3995549/14225785/a2ed772c-f8d7-11e5-9cf6-601c44e503e0.png)

**Comment by MarioZ** [comment]
Unfortunately I’m aware of this Windows security limitation, please note the following remarks that are mentioned in the Readme:

> If you are experiencing difficulties with viewing the CHM file's content after downloading it, right-click on CHM file, select "Properties" and under the "General" tab click "Unblock".

Does this solve your issue?
Also as an FYI, I was considering avoiding this behaviour by a CHM documentation in a ZIP file. The unzipped CHM file would not reproduce this issue.

**Comment by miere43** [comment]
Yep, everything works now.

Well, I didn't saw this text because I clicked link at the bottom of Readme saying "more details can be found in MadMilkman.Ini.Documentation.chm". Probably you should duplicate this text in the bottom of readme as well.
