### ISSUE TITLE
Apache License file not filled out

### ISSUE THREAD

**Issue by The009** [MarioZ/MadMilkman.Ini#8]
You have not properly filled out your Apache License file leaving us with nothing to properly include in our projects.

https://github.com/MarioZ/MadMilkman.Ini/blob/master/LICENSE#L178-L189

**Comment by MarioZ** [comment]
Apologize, I'll add this later today (after work) and let you know when it's done.

**Comment by MarioZ** [comment]
It is done, I hope this helps.
